/*
barometric-rook-works/

MANIFEST (for CODEX as build instructions)

Goal
- Turn this single-file React dashboard into a production Next.js site at https://barometer.rook.works
- Monetize via ads + optional freemium later
- No login required for v1

What is already done in this canvas
- A working React dashboard component with:
  - Future Dusk indigo/violet/black glass aesthetic
  - Hex grid background overlay
  - Dual unit formatting (inHg (hPa), F (C))
  - Station selector with "unknown station" error strip + fallback data
  - Lightweight dev tests (console.assert)

What CODEX should build around it (folder + files)

1) Next.js App Router scaffold
- Create folder: barometric-rook-works
- Use: Next.js 14+ (App Router), TypeScript, Tailwind
- Add shadcn/ui (Card, Button, Badge, Slider, Tabs, Tooltip)
- Add recharts + lucide-react

2) File tree (minimum viable)

barometric-rook-works/
  package.json
  next.config.js
  tsconfig.json
  tailwind.config.ts
  postcss.config.js
  app/
    layout.tsx
    page.tsx
    globals.css
    sitemap.ts
    robots.ts
  components/
    dashboard/BarometricDashboard.tsx        <-- this file content (from below)
  components/ui/                             <-- generated by shadcn
    (card.tsx, button.tsx, badge.tsx, slider.tsx, tabs.tsx, tooltip.tsx)
  public/
    og/barometer.png (optional)

3) Required deps (package.json)
- next, react, react-dom
- tailwindcss, postcss, autoprefixer
- recharts
- lucide-react
- class-variance-authority, clsx, tailwind-merge (shadcn typical)
- @radix-ui/* packages used by shadcn (tabs, tooltip, slider)

4) app/layout.tsx requirements
- Set metadata for SEO (title, description)
- OpenGraph + twitter card
- Add <html lang="en"> and body classes

5) app/page.tsx requirements
- Render <BarometricDashboard />
- Add a small text block under the dashboard for indexing (do not bury all text)

6) SEO pages (v1 minimal)
- CODEX should add routes:
  - /migraine-pressure-tracker
  - /faq
- Include FAQ JSON-LD on /faq
- Add internal links from / to those pages

7) Analytics + ads (do AFTER deploy)
- Add Plausible or GA4 (your call)
- Add AdSense placeholders but keep ads OUT of chart area

8) Real weather station data (NOT implemented here)
Reason: browser CORS will block most NOAA/NWS endpoints.
CODEX should implement a tiny server-side proxy route:
- app/api/station/[id]/route.ts
- Fetch from a reliable source (NOAA METAR, AviationWeather, NWS, etc)
- Normalize output into the Reading[] format used by the dashboard
- Return JSON to the client

9) Expected behavior for station loading (confirm)
- If station id is unknown OR API fails:
  - Show red strip: "Connection failed" + "Unknown station (XXXX)"
  - Continue to show mock fallback data

10) Known gaps / TODO (explicit)
- Persistent event log (migraine onset, meds) -> localStorage
- CSV export for event log + readings
- Threshold editor (risk model tuning)
- Alerts (requires email/push or at least browser notifications)

How CODEX should migrate this file
- Put the component below into: components/dashboard/BarometricDashboard.tsx
- In app/page.tsx:
  import BarometricDashboard from "@/components/dashboard/BarometricDashboard";
  export default function Page(){ return <BarometricDashboard /> }

Notes
- This component currently imports shadcn/ui paths like @/components/ui/card.
  CODEX must ensure those exist (via shadcn init + add).
- This component uses import.meta in dev-test detection; Next supports it in modern builds,
  but if it causes issues, gate dev tests on process.env.NODE_ENV only.
*/

import React, { useEffect, useMemo, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import PreparationTools from "@/components/PreparationTools";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  ResponsiveContainer,
  ReferenceDot,
  ReferenceLine,
} from "recharts";
import {
  CloudMoon,
  Droplets,
  Wind,
  Gauge,
  Activity,
  AlertTriangle,
  Info,
  ArrowUp,
  ArrowDown,
} from "lucide-react";

function clamp(n: number, a: number, b: number) {
  return Math.max(a, Math.min(b, n));
}

function round(n: number, d = 2) {
  const p = Math.pow(10, d);
  return Math.round(n * p) / p;
}

function formatTimeLabel(h: number) {
  const hour = ((h % 24) + 24) % 24;
  const ampm = hour >= 12 ? "PM" : "AM";
  const h12 = hour % 12 === 0 ? 12 : hour % 12;
  return `${h12} ${ampm}`;
}

function formatTimeLabelFromIso(iso: string) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return formatTimeLabel(d.getHours());
}

function inHgToHpa(inhg: number) {
  return inhg * 33.8638866667;
}

function fToC(f: number) {
  return (f - 32) * (5 / 9);
}

type Reading = {
  t: number;
  label: string;
  pressure_inhg: number;
  kind: "observed" | "forecast";
  temp_f: number;
  humidity: number;
  wind_mph: number;
};

type MigraineEventType = "onset" | "meds";

type MigraineEvent = {
  id: string;
  type: MigraineEventType;
  at: string;
  station: string;
  pressure_inhg: number;
  delta3h: number;
  delta6h: number;
  notes?: string;
};

type HistoryPoint = {
  t: string;
  pressure_inhg: number;
};

type ForecastPoint = {
  t: string;
  pressure_inhg: number;
};

type Station = {
  id: string;
  name: string;
  base: number;
  drift: number;
  noise: number;
};

const stations: Station[] = [
  { id: "KGSO", name: "Greensboro (KGSO)", base: 30.24, drift: -0.09, noise: 0.02 },
  { id: "KINT", name: "Winston-Salem (KINT)", base: 30.18, drift: -0.06, noise: 0.025 },
  { id: "KCLT", name: "Charlotte (KCLT)", base: 30.12, drift: -0.04, noise: 0.02 },
  { id: "KAVL", name: "Asheville (KAVL)", base: 29.98, drift: -0.03, noise: 0.03 },
  { id: "KRDU", name: "Raleigh-Durham (KRDU)", base: 30.20, drift: -0.05, noise: 0.02 },
];

function makeSampleSeries({ base = 30.24, drift = -0.08, noise = 0.02 } = {}) {
  const points: Reading[] = [];
  for (let i = 0; i < 24; i++) {
    const trend = (drift / 23) * i;
    const wobble = Math.sin(i / 3) * (noise / 2) + Math.cos(i / 5) * (noise / 3);
    const p = base + trend + wobble;
    points.push({
      t: i,
      label: formatTimeLabel(i - 23),
      pressure_inhg: round(p, 3),
      kind: "observed",
      temp_f: round(33 + Math.sin(i / 4) * 10, 1),
      humidity: round(55 + Math.cos(i / 6) * 10, 0),
      wind_mph: round(3 + Math.max(0, Math.sin(i / 4) * 5), 0),
    });
  }
  return points;
}

function calcDeltas(series: Reading[]) {
  const last = series[series.length - 1];
  const getNHoursAgo = (n: number) => series[Math.max(0, series.length - 1 - n)];
  const pNow = last.pressure_inhg;

  const p1 = getNHoursAgo(1).pressure_inhg;
  const p3 = getNHoursAgo(3).pressure_inhg;
  const p6 = getNHoursAgo(6).pressure_inhg;
  const p24 = getNHoursAgo(23).pressure_inhg;

  const d1 = pNow - p1;
  const d3 = pNow - p3;
  const d6 = pNow - p6;
  const d24 = pNow - p24;

  const roc1 = d1 / 1;
  const roc3 = d3 / 3;

  return { pNow, d1, d3, d6, d24, roc1, roc3 };
}

type TrendTone = "ok" | "warn" | "danger";

function classifyTrend(rocInHgPerHr: number): { label: string; tone: TrendTone } {
  const r = rocInHgPerHr;
  const abs = Math.abs(r);

  if (abs < 0.005) return { label: "Stable", tone: "ok" };
  if (r < 0) {
    if (abs < 0.02) return { label: "Slowly Falling", tone: "warn" };
    return { label: "Rapid Drop", tone: "danger" };
  }
  if (abs < 0.02) return { label: "Slowly Rising", tone: "warn" };
  return { label: "Rapid Rise", tone: "danger" };
}

function riskFromDeltas({
  d3,
  d6,
  roc3,
}: {
  d3: number;
  d6: number;
  roc3: number;
}): { label: string; tone: TrendTone } {
  const a3 = Math.abs(d3);
  const a6 = Math.abs(d6);
  const ar = Math.abs(roc3);

  let score = 0;
  if (a3 >= 0.08) score += 2;
  else if (a3 >= 0.05) score += 1;

  if (a6 >= 0.12) score += 2;
  else if (a6 >= 0.08) score += 1;

  if (ar >= 0.03) score += 2;
  else if (ar >= 0.02) score += 1;

  if (score <= 1) return { label: "Low", tone: "ok" };
  if (score <= 3) return { label: "Elevated", tone: "warn" };
  return { label: "High", tone: "danger" };
}

function toneClasses(tone: TrendTone) {
  if (tone === "danger") return "bg-red-600/90 text-[var(--text)]";
  if (tone === "warn") return "bg-yellow-500/90 text-[var(--text)]";
  return "bg-emerald-600/90 text-[var(--text)]";
}

function glassRiskTone(tone: TrendTone) {
  if (tone === "danger") return "border-red-500/30 bg-gradient-to-br from-red-500/10 via-transparent to-transparent";
  if (tone === "warn") return "border-yellow-500/30 bg-gradient-to-br from-yellow-500/10 via-transparent to-transparent";
  return "border-indigo-500/30 bg-gradient-to-br from-indigo-500/10 via-transparent to-transparent";
}

function findForecastAtOrAfter(series: ForecastPoint[], targetMs: number) {
  return series.find((p) => {
    const t = Date.parse(p.t);
    return Number.isFinite(t) && t >= targetMs;
  });
}

function computeForecastDeltas(series: ForecastPoint[] | null) {
  if (!series || series.length < 2) {
    return {
      delta3h: null as number | null,
      delta6h: null as number | null,
      peakShift: null as number | null,
      target3hTime: null as string | null,
    };
  }

  const start = series[0];
  const startMs = Date.parse(start.t);
  if (!Number.isFinite(startMs)) {
    return {
      delta3h: null,
      delta6h: null,
      peakShift: null,
      target3hTime: null,
    };
  }

  const t3 = startMs + 3 * 60 * 60 * 1000;
  const t6 = startMs + 6 * 60 * 60 * 1000;
  const end24 = startMs + 24 * 60 * 60 * 1000;

  const target3 = findForecastAtOrAfter(series, t3) ?? series[series.length - 1];
  const target6 = findForecastAtOrAfter(series, t6) ?? series[series.length - 1];

  let peakShift = 0;
  let hasPeak = false;
  for (const point of series) {
    const t = Date.parse(point.t);
    if (!Number.isFinite(t) || t > end24) continue;
    const delta = point.pressure_inhg - start.pressure_inhg;
    if (!hasPeak || Math.abs(delta) > Math.abs(peakShift)) {
      peakShift = delta;
      hasPeak = true;
    }
  }

  return {
    delta3h: target3.pressure_inhg - start.pressure_inhg,
    delta6h: target6.pressure_inhg - start.pressure_inhg,
    peakShift: hasPeak ? peakShift : null,
    target3hTime: target3.t ?? null,
  };
}

function buildObservedSeries(points: HistoryPoint[], fallback: Reading) {
  return points.map((p, idx) => ({
    t: idx,
    label: formatTimeLabelFromIso(p.t),
    pressure_inhg: round(p.pressure_inhg, 3),
    kind: "observed" as const,
    temp_f: fallback.temp_f,
    humidity: fallback.humidity,
    wind_mph: fallback.wind_mph,
  }));
}

function buildForecastSeries(points: ForecastPoint[], startIndex: number, fallback: Reading) {
  return points.map((p, idx) => ({
    t: startIndex + idx,
    label: formatTimeLabelFromIso(p.t),
    pressure_inhg: round(p.pressure_inhg, 3),
    kind: "forecast" as const,
    temp_f: fallback.temp_f,
    humidity: fallback.humidity,
    wind_mph: fallback.wind_mph,
  }));
}

const EVENT_KEY = "rook.migraine.events.v1";

function loadEvents(): MigraineEvent[] {
  try {
    if (typeof window === "undefined" || !window.localStorage) return [];
    const raw = window.localStorage.getItem(EVENT_KEY);
    return raw ? (JSON.parse(raw) as MigraineEvent[]) : [];
  } catch {
    return [];
  }
}

function saveEvents(events: MigraineEvent[]) {
  try {
    if (typeof window === "undefined" || !window.localStorage) return;
    window.localStorage.setItem(EVENT_KEY, JSON.stringify(events));
  } catch {
    // ignore storage failures
  }
}

function makeEventId() {
  try {
    if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
      return crypto.randomUUID();
    }
  } catch {}
  return `evt_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function formatLocalTimestamp(iso: string) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString();
}

// Future: consider IndexedDB, pain scale (1-10), optional notes, and export merge with pressure history.

function MetricPill({
  label,
  value,
  hint,
}: {
  label: string;
  value: React.ReactNode;
  hint?: string;
}) {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <div
            className={
              "flex items-center justify-between rounded-xl border backdrop-blur px-3 py-2 " +
              "shadow-[0_0_0_1px_rgba(255,255,255,0.05),inset_0_1px_0_rgba(255,255,255,0.06)]"
            }
            style={{ background: "var(--surface2)", borderColor: "var(--border)" }}
          >
            <div className="text-xs" style={{ color: "var(--muted)" }}>
              {label}
            </div>
            <div className="font-semibold tabular-nums" style={{ color: "var(--text)" }}>
              {value}
            </div>
          </div>
        </TooltipTrigger>
        {hint ? (
          <TooltipContent
            className="max-w-xs"
            style={{ background: "var(--surface)", borderColor: "var(--border)", color: "var(--text)" }}
          >
            {hint}
          </TooltipContent>
        ) : null}
      </Tooltip>
    </TooltipProvider>
  );
}

function BigCardHeader({
  title,
  subtitle,
  icon: Icon,
}: {
  title: string;
  subtitle: string;
  icon: React.ElementType;
}) {
  return (
    <div className="flex items-start justify-between gap-3">
      <div>
        <div className="text-sm" style={{ color: "var(--muted)" }}>
          {title}
        </div>
        <div className="text-2xl font-semibold leading-tight" style={{ color: "var(--text)" }}>
          {subtitle}
        </div>
      </div>
      <div
        className="rounded-2xl border p-2 shadow-[inset_0_1px_0_rgba(255,255,255,0.06)]"
        style={{ background: "var(--surface2)", borderColor: "var(--border)" }}
      >
        <Icon className="h-5 w-5" style={{ color: "var(--text)" }} />
      </div>
    </div>
  );
}

function fmtDualPressure(inHg: number) {
  return `${round(inHg, 2)} inHg (${round(inHgToHpa(inHg), 1)} hPa)`;
}

function fmtDualTemp(f: number) {
  return `${round(f, 1)} F (${round(fToC(f), 1)} C)`;
}

function fmtDualDelta(inHgDelta: number) {
  const sign = inHgDelta >= 0 ? "+" : "";
  const inTxt = `${sign}${round(inHgDelta, 2)} in`;
  const hpaTxt = `${sign}${round(inHgToHpa(inHgDelta), 1)} hPa`;
  return `${inTxt} (${hpaTxt})`;
}

function fmtDualRate(inHgPerHr: number) {
  const sign = inHgPerHr >= 0 ? "+" : "";
  const inTxt = `${sign}${round(inHgPerHr, 3)} in/hr`;
  const hpaTxt = `${sign}${round(inHgToHpa(inHgPerHr), 2)} hPa/hr`;
  return `${inTxt} (${hpaTxt})`;
}

function runDevTests() {
  console.assert(clamp(5, 0, 10) === 5, "clamp basic");
  console.assert(clamp(-1, 0, 10) === 0, "clamp lower bound");
  console.assert(clamp(99, 0, 10) === 10, "clamp upper bound");

  console.assert(round(30.236, 2) === 30.24, "round 2dp");
  console.assert(round(30.231, 2) === 30.23, "round 2dp down");

  console.assert(Math.abs(inHgToHpa(30) - 1015.9) < 0.5, "inHg->hPa rough");
  console.assert(Math.abs(fToC(32) - 0) < 1e-9, "F->C freezing");

  console.assert(normalizeStationId(" k-gso ") === "KGSO", "normalizeStationId strips symbols");
  console.assert(normalizeStationId("kavl!!") === "KAVL", "normalizeStationId uppercases");

  console.assert(classifyTrend(0).label === "Stable", "trend stable");
  console.assert(classifyTrend(-0.03).label === "Rapid Drop", "trend rapid drop");
  console.assert(classifyTrend(0.03).label === "Rapid Rise", "trend rapid rise");

  console.assert(
    riskFromDeltas({ d3: 0.01, d6: 0.01, roc3: 0.001 }).label === "Low",
    "risk low"
  );
  console.assert(
    riskFromDeltas({ d3: 0.06, d6: 0.09, roc3: 0.021 }).label !== "Low",
    "risk not low"
  );

  console.assert(
    fmtDualPressure(30.16).includes("inHg") && fmtDualPressure(30.16).includes("hPa"),
    "dual pressure format"
  );
  console.assert(
    fmtDualRate(-0.001).includes("in/hr") && fmtDualRate(-0.001).includes("hPa/hr"),
    "dual rate format"
  );

  console.assert(fmtDualDelta(0.01).startsWith("+"), "delta plus sign");
  console.assert(!fmtDualDelta(-0.01).startsWith("+"), "delta minus no plus");
}

try {
  const isDev =
    typeof process !== "undefined" && process.env && process.env.NODE_ENV === "development";
  if (typeof window !== "undefined" && isDev) runDevTests();
} catch {
  // ignore
}

function normalizeStationId(raw: string) {
  return raw.trim().toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6);
}

export default function BarometricDashboard() {
  const [range, setRange] = useState<"6h" | "12h" | "24h">("24h");
  const [events, setEvents] = useState<MigraineEvent[]>([]);

  type StationLoadState = "idle" | "loading" | "ok" | "error";
  const [stationLoadState, setStationLoadState] = useState<StationLoadState>("idle");
  const [stationError, setStationError] = useState<string>("");
  const [liveObs, setLiveObs] = useState<null | {
    pressure_inhg: number;
    temp_f: number;
    wind_mph: number | null;
    humidity: number | null;
    observedAt: string | null;
  }>(null);

  const [historySeries, setHistorySeries] = useState<Reading[] | null>(null);
  const [forecastSeries, setForecastSeries] = useState<ForecastPoint[] | null>(null);

  const [stationId, setStationId] = useState<string>("KGSO");
  const [customStation, setCustomStation] = useState<string>("");

  const activeStation = useMemo(() => {
    const found = stations.find((s) => s.id === stationId);
    return found ?? stations[0];
  }, [stationId]);

const isKnownStation = useMemo(() => stations.some((s) => s.id === stationId), [stationId]);

const stationCaption = useMemo(() => {
  if (stationLoadState === "loading") return `Loading ${stationId}...`;
  if (stationLoadState === "error") return `Unknown station (${stationId})`;

  // API succeeded; if it's not in our preset list, still show it as valid.
  if (!isKnownStation) return `${stationId} (live)`;

  return activeStation.name;
}, [stationId, stationLoadState, isKnownStation, activeStation.name]);

  async function loadStationFromApi(nextId: string) {
    const res = await fetch(`/api/station/${encodeURIComponent(nextId)}`, {
      headers: { Accept: "application/json" },
    });

    if (!res.ok) {
      let msg = "Connection failed";
      try {
        const j = await res.json();
        if (j?.error) msg = String(j.error);
      } catch {}
      throw new Error(msg);
    }

    const j = await res.json();
    return j as {
      station: string;
      location?: { lat: number | null; lon: number | null } | null;
      observedAt: string | null;
      pressure_inhg: number;
      temp_f: number;
      wind_mph: number | null;
      humidity: number | null;
    };
  }

  async function loadStationHistory(nextId: string) {
    const res = await fetch(`/api/history/${encodeURIComponent(nextId)}?hours=24`, {
      headers: { Accept: "application/json" },
    });

    if (!res.ok) {
      let msg = "History unavailable";
      try {
        const j = await res.json();
        if (j?.error) msg = String(j.error);
      } catch {}
      throw new Error(msg);
    }

    const j = await res.json();
    return j as {
      station: string;
      points: HistoryPoint[];
    };
  }

  async function loadForecast(nextId: string, hours = 12) {
    const res = await fetch(
      `/api/forecast/${encodeURIComponent(nextId)}?hours=${encodeURIComponent(hours)}`,
      { headers: { Accept: "application/json" } }
    );

    if (!res.ok) {
      let msg = "Forecast unavailable";
      try {
        const j = await res.json();
        if (j?.error) msg = String(j.error);
      } catch {}
      throw new Error(msg);
    }

    const j = await res.json();
    return j as {
      points: ForecastPoint[];
    };
  }

  async function applyStation(nextIdRaw: string) {
    const nextId = normalizeStationId(nextIdRaw);
    if (!nextId) return;

    setStationId(nextId);
    setStationError("");
    setStationLoadState("loading");
    setHistorySeries(null);
    setForecastSeries(null);

    try {
      const obs = await loadStationFromApi(nextId);
      setLiveObs({
        pressure_inhg: obs.pressure_inhg,
        temp_f: obs.temp_f,
        wind_mph: obs.wind_mph,
        humidity: obs.humidity,
        observedAt: obs.observedAt,
      });
      try {
        const forecast = await loadForecast(nextId, 12);
        setForecastSeries(forecast.points ?? null);
      } catch {}

      try {
        const history = await loadStationHistory(nextId);
        if (history.points.length > 0) {
          const fallback = sampleReadings[sampleReadings.length - 1];
          const fallbackReading = {
            ...fallback,
            pressure_inhg: obs.pressure_inhg,
            temp_f: obs.temp_f,
            humidity: obs.humidity ?? fallback.humidity,
            wind_mph: obs.wind_mph ?? fallback.wind_mph,
          };
          setHistorySeries(buildObservedSeries(history.points, fallbackReading));
        }
      } catch {}

      setStationLoadState("ok");
    } catch (e) {
      setStationLoadState("error");
      setStationError(e instanceof Error ? e.message : "Connection failed");
      setLiveObs(null);
    }
  }

  useEffect(() => {
    void applyStation("KGSO");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    setEvents(loadEvents());
  }, []);

  const [sensitivity, setSensitivity] = useState<number[]>([60]);

  const sampleReadings = useMemo(
    () =>
      makeSampleSeries({
        base: activeStation.base,
        drift: activeStation.drift,
        noise: activeStation.noise,
      }),
    [activeStation]
  );

  const observedSeries = useMemo(() => {
    if (historySeries && historySeries.length) return historySeries;
    return sampleReadings;
  }, [historySeries, sampleReadings]);

  const observedRange = useMemo(() => {
    if (range === "12h") return observedSeries.slice(-12);
    if (range === "6h") return observedSeries.slice(-6);
    return observedSeries;
  }, [observedSeries, range]);

  const forecastReadings = useMemo(() => {
    if (!forecastSeries || forecastSeries.length === 0) return [];
    const fallback = observedRange[observedRange.length - 1] ?? sampleReadings[sampleReadings.length - 1];
    const lastObservedT = observedRange[observedRange.length - 1]?.t ?? 0;
    return buildForecastSeries(forecastSeries, lastObservedT + 1, fallback);
  }, [forecastSeries, observedRange, sampleReadings]);

  const chartSeries = useMemo(
    () => [...observedRange, ...forecastReadings],
    [observedRange, forecastReadings]
  );

  const { pNow, d1, d3, d6, d24, roc1, roc3 } = useMemo(
    () => calcDeltas(observedRange),
    [observedRange]
  );

  const trend = useMemo(() => classifyTrend(roc3), [roc3]);

  const adjusted = useMemo(() => {
    const k = clamp(sensitivity[0] / 60, 0.6, 1.6);
    return {
      d3: d3 * k,
      d6: d6 * k,
      roc3: roc3 * k,
    };
  }, [d3, d6, roc3, sensitivity]);

  const risk = useMemo(() => riskFromDeltas(adjusted), [adjusted]);
  const forecastDeltas = useMemo(() => computeForecastDeltas(forecastSeries), [forecastSeries]);
  const forecastDelta3h = forecastDeltas.delta3h;
  const forecastDelta6h = forecastDeltas.delta6h;
  const forecastPeakShift = forecastDeltas.peakShift;
  const riskLabelForPrep = (risk.label === "Elevated" ? "Moderate" : risk.label) as
    | "Low"
    | "Moderate"
    | "High";
  const riskLabelForSummary = riskLabelForPrep;

  const primaryDriver =
    roc3 < -0.02
      ? "Rapid pressure drop over the last 3 hours"
      : roc3 > 0.02
        ? "Rapid pressure rise over the last 3 hours"
        : "Minor pressure changes";

  const forecastPrimaryDelta = forecastDelta3h ?? forecastDelta6h ?? forecastPeakShift;
  const forecastDirection =
    typeof forecastPrimaryDelta === "number" ? (forecastPrimaryDelta >= 0 ? "up" : "down") : null;
  const forecastDeltaDisplay =
    typeof forecastPrimaryDelta === "number"
      ? `${forecastPrimaryDelta >= 0 ? "+" : ""}${round(forecastPrimaryDelta, 2)} inHg`
      : "Forecast unavailable";
  const forecastWindowLabel = forecastDeltas.target3hTime
    ? `By ${formatTimeLabelFromIso(forecastDeltas.target3hTime)}`
    : "Next 3 hours";
  const forecastHeadline =
    typeof forecastPrimaryDelta === "number"
      ? `Pressure ${forecastPrimaryDelta >= 0 ? "rising" : "falling"} over the next 3 hours.`
      : "Forecast data unavailable.";
  const forecastHint =
    typeof forecastPrimaryDelta !== "number"
      ? "Forecast data unavailable for this station."
      : Math.abs(forecastPrimaryDelta) < 0.03
        ? "Small shift expected; plan as usual."
        : forecastPrimaryDelta < 0
          ? "Falling pressure often correlates with headaches."
          : "Rising pressure may bring relief for some people.";

  const last = observedRange[observedRange.length - 1];

  const livePressure = liveObs?.pressure_inhg ?? pNow;
  const liveTempF = liveObs?.temp_f ?? last.temp_f;
  const liveWind = liveObs?.wind_mph ?? last.wind_mph;
  const liveHumidity = liveObs?.humidity ?? last.humidity;

  const nowLabel = observedRange[observedRange.length - 1]?.label;
  const nowT = observedRange[observedRange.length - 1]?.t;

  const tempDisplay = fmtDualTemp(liveTempF);
  const pressureDisplay = fmtDualPressure(livePressure);
  const asOfLabel = liveObs?.observedAt
    ? `As of ${formatTimeLabelFromIso(liveObs.observedAt)}`
    : nowLabel
      ? `As of ${nowLabel}`
      : null;

  function logEvent(type: MigraineEventType) {
    const entry: MigraineEvent = {
      id: makeEventId(),
      type,
      at: new Date().toISOString(),
      station: stationId,
      pressure_inhg: livePressure,
      delta3h: d3,
      delta6h: d6,
    };

    const next = [...events, entry];
    setEvents(next);
    saveEvents(next);
  }

  function exportEventsCsv() {
    if (events.length === 0) return;
    const rows = [
      ["timestamp", "event_type", "station", "pressure_inhg", "delta_3h", "delta_6h"],
      ...events.map((event) => [
        event.at,
        event.type,
        event.station,
        round(event.pressure_inhg, 3).toString(),
        round(event.delta3h, 3).toString(),
        round(event.delta6h, 3).toString(),
      ]),
    ];

    const csv = rows.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "migraine-log.csv";
    a.click();
    URL.revokeObjectURL(url);
  }

  const eventDots = useMemo(() => {
    const onsetT = observedRange[Math.max(0, observedRange.length - 9)]?.t;
    const medsT = observedRange[Math.max(0, observedRange.length - 7)]?.t;
    return [
      { t: onsetT, kind: "onset" as const, label: "Migraine onset" },
      { t: medsT, kind: "med" as const, label: "Meds" },
    ].filter((e) => typeof e.t === "number");
  }, [observedRange]);

  const recentEvents = useMemo(() => events.slice(-5).reverse(), [events]);

  return (
    <div
      className="min-h-screen w-full p-4 md:p-6"
      style={{ background: "var(--bg-gradient)", color: "var(--text)" }}
    >
      <div className="pointer-events-none fixed inset-0">
        <div
          className="absolute inset-0 opacity-[0.12]"
          style={{
            backgroundImage:
              "linear-gradient(60deg, rgba(255,255,255,0.22) 1px, transparent 1px)," +
              "linear-gradient(-60deg, rgba(255,255,255,0.22) 1px, transparent 1px)," +
              "linear-gradient(0deg, rgba(255,255,255,0.18) 1px, transparent 1px)",
            backgroundSize: "64px 36px, 64px 36px, 64px 36px",
            backgroundPosition: "0 0, 0 0, 0 0",
          }}
        />
        <div className="absolute inset-0 opacity-[0.10] [background-image:radial-gradient(circle_at_1px_1px,rgba(255,255,255,0.45)_1px,transparent_1.9px)] [background-size:32px_32px]" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,transparent_0%,rgba(0,0,0,0.38)_68%,rgba(0,0,0,0.70)_100%)]" />
      </div>

      <div className="relative mx-auto max-w-6xl">
        {stationLoadState === "error" ? (
          <div className="mb-3 rounded-2xl border border-red-500/30 bg-red-600/20 px-4 py-2 text-sm text-red-50 shadow-[0_0_0_1px_rgba(255,255,255,0.04),inset_0_1px_0_rgba(255,255,255,0.06)]">
            <span className="font-semibold">Connection failed.</span> {stationError || "Unknown station."}{" "}
            <span className="text-red-100/80">Showing mock fallback data.</span>
          </div>
        ) : null}

        <div className="mb-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <div className="text-sm" style={{ color: "var(--muted)" }}>
              {stationCaption}
            </div>
            <div className="text-2xl font-semibold" style={{ color: "var(--text)" }}>
              Barometric Pressure & Migraine Risk
            </div>
            <div className="text-sm" style={{ color: "var(--muted)" }}>
              Today&apos;s pressure trend suggests a {riskLabelForSummary} migraine risk.
            </div>
            <div className="text-xs" style={{ color: "var(--muted)" }}>
              Please use station ID field to select your nearest ICAO station for best information.
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <div
              className="flex flex-wrap items-center gap-2 rounded-2xl border backdrop-blur px-3 py-2 shadow-[0_0_0_1px_rgba(255,255,255,0.04),inset_0_1px_0_rgba(255,255,255,0.06)]"
              style={{ background: "var(--surface)", borderColor: "var(--border)" }}
            >
              <div className="text-xs" style={{ color: "var(--muted)" }}>
                Station
              </div>
              <select
                value={stationId}
                onChange={(e) => void applyStation(e.target.value)}
                className="h-8 rounded-xl border px-2 text-xs outline-none"
                style={{ background: "var(--surface2)", borderColor: "var(--border)", color: "var(--text)" }}
              >
                {stations.map((s) => (
                  <option key={s.id} value={s.id} className="bg-[var(--bg)] text-[var(--text)]">
                    {s.id}
                  </option>
                ))}
              </select>
              <div className="h-5 w-px" style={{ background: "var(--border)" }} />
              <input
                value={customStation}
                onChange={(e) => setCustomStation(e.target.value)}
                placeholder="Custom ICAO (e.g., KAVL)"
                className="h-8 w-44 rounded-xl border px-2 text-xs placeholder:text-[var(--muted)] outline-none"
                style={{ background: "var(--surface2)", borderColor: "var(--border)", color: "var(--text)" }}
              />
              <Button
                variant="outline"
                disabled={stationLoadState === "loading"}
                className="h-8 rounded-xl border px-3 text-xs hover:opacity-90 disabled:opacity-60"
                style={{ background: "var(--surface2)", borderColor: "var(--border)", color: "var(--text)" }}
                onClick={() => void applyStation(customStation)}
              >
                {stationLoadState === "loading" ? "Loading..." : "Load"}
              </Button>
            </div>

            <Tabs value={range} onValueChange={(v) => setRange(v as typeof range)}>
              <TabsList
                className="rounded-2xl border"
                style={{ background: "var(--surface2)", borderColor: "var(--border)" }}
              >
                <TabsTrigger
                  value="6h"
                  className="rounded-xl text-xs text-[var(--muted)] data-[state=active]:bg-[var(--surface)] data-[state=active]:text-[var(--text)] data-[state=active]:font-semibold data-[state=active]:ring-1 data-[state=active]:ring-[var(--border)]"
                >
                  6h
                </TabsTrigger>
                <TabsTrigger
                  value="12h"
                  className="rounded-xl text-xs text-[var(--muted)] data-[state=active]:bg-[var(--surface)] data-[state=active]:text-[var(--text)] data-[state=active]:font-semibold data-[state=active]:ring-1 data-[state=active]:ring-[var(--border)]"
                >
                  12h
                </TabsTrigger>
                <TabsTrigger
                  value="24h"
                  className="rounded-xl text-xs text-[var(--muted)] data-[state=active]:bg-[var(--surface)] data-[state=active]:text-[var(--text)] data-[state=active]:font-semibold data-[state=active]:ring-1 data-[state=active]:ring-[var(--border)]"
                >
                  24h
                </TabsTrigger>
              </TabsList>
            </Tabs>

            <div
              className="flex items-center gap-2 rounded-2xl border backdrop-blur px-3 py-2 shadow-[0_0_0_1px_rgba(255,255,255,0.04),inset_0_1px_0_rgba(255,255,255,0.06)]"
              style={{ background: "var(--surface)", borderColor: "var(--border)" }}
            >
              <span className="text-[10px] uppercase tracking-wide" style={{ color: "var(--muted)" }}>
                Pressure: inHg (hPa)
              </span>
              <span className="text-[10px] uppercase tracking-wide" style={{ color: "var(--muted)" }}>
                Temp: F (C)
              </span>
            </div>

            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <div
                    className="flex items-center gap-2 rounded-2xl border backdrop-blur px-3 py-2 shadow-[0_0_0_1px_rgba(255,255,255,0.04),inset_0_1px_0_rgba(255,255,255,0.06)]"
                    style={{ background: "var(--surface)", borderColor: "var(--border)" }}
                  >
                    <Activity className="h-4 w-4" style={{ color: "var(--text)" }} />
                    <div className="text-xs">
                      <div style={{ color: "var(--muted)" }}>Sensitivity</div>
                      <div className="font-semibold" style={{ color: "var(--text)" }}>
                        {sensitivity[0]}%
                      </div>
                    </div>
                    <div className="w-36">
                      <Slider value={sensitivity} onValueChange={setSensitivity} min={20} max={100} step={1} />
                    </div>
                  </div>
                </TooltipTrigger>
                <TooltipContent
                  className="max-w-sm"
                  style={{ background: "var(--surface)", borderColor: "var(--border)", color: "var(--text)" }}
                >
                  Demo knob: scales deltas and rate before risk scoring. Real use should tune thresholds instead.
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          <Card
            className={`md:col-span-2 rounded-3xl border ${glassRiskTone(
              risk.tone
            )} backdrop-blur shadow-[0_0_0_1px_rgba(255,255,255,0.05),inset_0_1px_0_rgba(255,255,255,0.06),0_20px_60px_rgba(0,0,0,0.55)]`}
            style={{ backgroundColor: "var(--surface)" }}
          >
            <CardHeader className="pb-2">
              <div className="flex items-start justify-between gap-3">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <Badge className={`rounded-xl text-sm font-semibold ${toneClasses(risk.tone)}`}>
                      Migraine Risk: {risk.label}
                    </Badge>
                    <Badge
                      variant="outline"
                      className="rounded-xl border"
                      style={{ background: "var(--surface2)", borderColor: "var(--border)", color: "var(--text)" }}
                    >
                      Trend: {trend.label}
                    </Badge>
                  </div>
                  <div className="text-xs" style={{ color: "var(--muted)" }}>
                    Primary driver: {primaryDriver}
                  </div>

                  <CardTitle className="text-2xl font-medium drop-shadow-[0_1px_2px_rgba(0,0,0,0.65)]" style={{ color: "var(--text)" }}>
                    {pressureDisplay}
                  </CardTitle>
                  {asOfLabel ? (
                    <div className="text-xs" style={{ color: "var(--muted)" }}>
                      {asOfLabel}
                    </div>
                  ) : null}

                  <div className="flex items-center gap-2 text-sm" style={{ color: "var(--muted)" }}>
                    <Gauge className="h-4 w-4" style={{ color: "var(--text)" }} />
                    <span>Rate: {fmtDualRate(roc3)} (3h avg)</span>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <div
                    className="rounded-2xl border p-2"
                    style={{ background: "var(--surface2)", borderColor: "var(--border)" }}
                  >
                    <AlertTriangle className="h-5 w-5" style={{ color: "var(--text)" }} />
                  </div>
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <div
                          className="rounded-2xl border p-2 cursor-help"
                          style={{ background: "var(--surface2)", borderColor: "var(--border)" }}
                        >
                          <Info className="h-5 w-5" style={{ color: "var(--text)" }} />
                        </div>
                      </TooltipTrigger>
                      <TooltipContent
                        className="max-w-sm"
                        style={{ background: "var(--surface)", borderColor: "var(--border)", color: "var(--text)" }}
                      >
                        This estimate is based on recent barometric pressure changes. Many people report migraines
                        during rapid pressure shifts, but responses vary by individual. This tool is informational
                        only.
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </div>
              </div>
            </CardHeader>

            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-2 md:grid-cols-4">
                <MetricPill label="Delta 1h" value={fmtDualDelta(d1)} hint="Current pressure minus 1 hour ago." />
                <MetricPill label="Delta 3h" value={fmtDualDelta(d3)} hint="Current pressure minus 3 hours ago." />
                <MetricPill label="Delta 6h" value={fmtDualDelta(d6)} hint="Current pressure minus 6 hours ago." />
                <MetricPill label="Delta 24h" value={fmtDualDelta(d24)} hint="Current pressure minus 24 hours ago." />
              </div>

              <div
                className="h-64 md:h-72 w-full rounded-2xl border backdrop-blur p-3 shadow-[inset_0_1px_0_rgba(255,255,255,0.06)]"
                style={{ background: "var(--surface2)", borderColor: "var(--border)" }}
              >
                <div className="mb-2 flex items-center justify-between">
                  <div className="text-sm font-semibold" style={{ color: "var(--text)" }}>
                    Pressure trend
                  </div>
                  <div className="text-xs" style={{ color: "var(--muted)" }}>
                    Chart axis in inHg (hPa shown on cards)
                  </div>
                </div>
                <div className="mb-2 text-[11px]" style={{ color: "var(--muted)" }}>
                  Viewing: Last {range === "6h" ? "6" : range === "12h" ? "12" : "24"} hours
                </div>
                <div className="mb-2 text-[11px]" style={{ color: "var(--muted)" }}>
                  Forecast values are estimates and may change.
                </div>

                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={chartSeries} margin={{ top: 10, right: 10, bottom: 0, left: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" opacity={0.25} />
                    <XAxis
                      dataKey="t"
                      type="number"
                      domain={["dataMin", "dataMax"]}
                      tick={{ fontSize: 12, fill: "var(--muted)" }}
                      interval="preserveStartEnd"
                      tickFormatter={(t: number) => {
                        const point = chartSeries.find((p) => p.t === t);
                        return point ? point.label : "";
                      }}
                    />
                    <YAxis
                      domain={["dataMin", "dataMax"]}
                      tick={{ fontSize: 12, fill: "var(--muted)" }}
                      width={52}
                      tickFormatter={(v: number) => v.toFixed(2)}
                    />
                    {typeof nowT === "number" ? (
                      <ReferenceLine
                        x={nowT}
                        stroke="rgba(177,147,255,0.9)"
                        strokeDasharray="4 4"
                        label={{ value: "Now", position: "top" }}
                      />
                    ) : null}
                    <Line
                      data={chartSeries.filter((p) => p.kind === "observed")}
                      type="monotone"
                      dataKey="pressure_inhg"
                      stroke="rgba(177,147,255,0.95)"
                      strokeWidth={2.6}
                      dot={false}
                    />
                    <Line
                      data={chartSeries.filter((p) => p.kind === "forecast")}
                      type="monotone"
                      dataKey="pressure_inhg"
                      stroke="rgba(177,147,255,0.55)"
                      strokeDasharray="6 6"
                      strokeWidth={2}
                      dot={false}
                    />

                    {eventDots.map((e, idx) => {
                      const point = observedRange.find((p) => p.t === e.t);
                      if (!point) return null;
                      return (
                        <ReferenceDot
                          key={idx}
                          x={point.label}
                          y={point.pressure_inhg}
                          r={6}
                          fill={e.kind === "onset" ? "rgba(185,76,59,0.95)" : "rgba(217,201,29,0.95)"}
                          stroke="rgba(0,0,0,0.25)"
                          ifOverflow="extendDomain"
                        />
                      );
                    })}
                  </LineChart>
                </ResponsiveContainer>
              </div>

              <div className="flex flex-wrap gap-2">
                <Button
                  variant="outline"
                  className="rounded-2xl border hover:opacity-90"
                  style={{ background: "var(--surface2)", borderColor: "var(--border)", color: "var(--text)" }}
                  onClick={() => logEvent("onset")}
                >
                  Log migraine onset
                </Button>
                <Button
                  variant="outline"
                  className="rounded-2xl border hover:opacity-90"
                  style={{ background: "var(--surface2)", borderColor: "var(--border)", color: "var(--text)" }}
                  onClick={() => logEvent("meds")}
                >
                  Log meds
                </Button>
                <Button
                  variant="outline"
                  className="rounded-2xl border hover:opacity-90"
                  style={{ background: "var(--surface2)", borderColor: "var(--border)", color: "var(--text)" }}
                  onClick={exportEventsCsv}
                >
                  Export CSV
                </Button>
              </div>

              <div
                className="rounded-2xl border px-3 py-2 text-xs"
                style={{ background: "var(--surface2)", borderColor: "var(--border)", color: "var(--muted)" }}
              >
                <div className="mb-1 text-[11px] uppercase tracking-wide" style={{ color: "var(--muted)" }}>
                  Migraine Log
                </div>
                {recentEvents.length ? (
                  <div className="space-y-1">
                    {recentEvents.map((event) => (
                      <div key={event.id}>
                        {formatLocalTimestamp(event.at)} — {event.type} @ {round(event.pressure_inhg, 2)} inHg
                      </div>
                    ))}
                  </div>
                ) : (
                  <div>No events logged yet.</div>
                )}
              </div>

            </CardContent>
          </Card>

          <div className="grid grid-cols-1 gap-4">
            <Card
              className="rounded-3xl backdrop-blur border border-indigo-500/30 bg-gradient-to-br from-indigo-500/15 via-transparent to-transparent shadow-[0_0_0_1px_rgba(255,255,255,0.05),inset_0_1px_0_rgba(255,255,255,0.06),0_18px_48px_rgba(0,0,0,0.55)]"
              style={{ backgroundColor: "var(--surface)" }}
            >
              <CardContent className="p-5 space-y-3">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <div className="text-sm" style={{ color: "var(--muted)" }}>
                      Upcoming Pressure Shift
                    </div>
                    <div className="text-3xl font-semibold" style={{ color: "var(--text)" }}>
                      {forecastDeltaDisplay}
                    </div>
                    <div className="text-xs" style={{ color: "var(--muted)" }}>
                      {forecastWindowLabel}
                    </div>
                  </div>
                  <div
                    className="rounded-2xl border p-2"
                    style={{ background: "var(--surface2)", borderColor: "var(--border)" }}
                  >
                    {forecastDirection === "up" ? (
                      <ArrowUp className="h-5 w-5 text-emerald-300" />
                    ) : forecastDirection === "down" ? (
                      <ArrowDown className="h-5 w-5 text-rose-300" />
                    ) : (
                      <Info className="h-5 w-5" style={{ color: "var(--text)" }} />
                    )}
                  </div>
                </div>
                <div className="text-xs" style={{ color: "var(--muted)" }}>
                  {forecastHeadline}
                </div>
                <div className="text-xs" style={{ color: "var(--muted)" }}>
                  Risk hint: {forecastHint}
                </div>
              </CardContent>
            </Card>

            <Card
              className="rounded-3xl backdrop-blur border shadow-[0_0_0_1px_rgba(255,255,255,0.05),inset_0_1px_0_rgba(255,255,255,0.06),0_18px_48px_rgba(0,0,0,0.55)]"
              style={{ background: "var(--surface)", borderColor: "var(--border)" }}
            >
              <CardContent className="p-5 space-y-3">
                <BigCardHeader title="Conditions" subtitle={`Clear, ${tempDisplay}`} icon={CloudMoon} />
                <div className="grid grid-cols-2 gap-2">
                  <MetricPill label="AQI" value="32" hint="Optional. Add if you track it." />
                  <MetricPill label="UV" value="2" hint="Optional." />
                </div>
              </CardContent>
            </Card>

            <Card
              className="rounded-3xl backdrop-blur border shadow-[0_0_0_1px_rgba(255,255,255,0.05),inset_0_1px_0_rgba(255,255,255,0.06),0_18px_48px_rgba(0,0,0,0.55)]"
              style={{ background: "var(--surface)", borderColor: "var(--border)" }}
            >
              <CardContent className="p-5 space-y-3">
                <BigCardHeader title="Wind" subtitle={`${liveWind} mph`} icon={Wind} />
                <div className="grid grid-cols-2 gap-2">
                  <MetricPill label="Gust" value="11 mph" hint="Mock value." />
                  <MetricPill label="Direction" value="NE" hint="Mock value." />
                </div>
              </CardContent>
            </Card>

            <Card
              className="rounded-3xl backdrop-blur border shadow-[0_0_0_1px_rgba(255,255,255,0.05),inset_0_1px_0_rgba(255,255,255,0.06),0_18px_48px_rgba(0,0,0,0.55)]"
              style={{ background: "var(--surface)", borderColor: "var(--border)" }}
            >
              <CardContent className="p-5 space-y-3">
                <BigCardHeader title="Humidity" subtitle={`${liveHumidity}%`} icon={Droplets} />
                <div className="grid grid-cols-2 gap-2">
                  <MetricPill label="Dew point" value={fmtDualTemp(21)} hint="Mock value." />
                  <MetricPill label="Comfort" value="Normal" hint="Optional labeling." />
                </div>
              </CardContent>
            </Card>

            <Card
              className="rounded-3xl backdrop-blur border shadow-[0_0_0_1px_rgba(255,255,255,0.05),inset_0_1px_0_rgba(255,255,255,0.06),0_18px_48px_rgba(0,0,0,0.55)]"
              style={{ background: "var(--surface)", borderColor: "var(--border)" }}
            >
              <CardContent className="p-5 space-y-3">
                <BigCardHeader title="Pressure status" subtitle={trend.label} icon={Gauge} />
                <div className="grid grid-cols-2 gap-2">
                  <MetricPill label="Rate (1h)" value={fmtDualRate(roc1)} hint="Short-term rate." />
                  <MetricPill label="Rate (3h)" value={fmtDualRate(roc3)} hint="Smoothed rate." />
                </div>
              </CardContent>
            </Card>

            <div className="rounded-2xl">
              <div className="mb-2 text-xs font-semibold" style={{ color: "var(--muted)" }}>
                Recommended preparation (based on today&apos;s risk)
              </div>
              <PreparationTools risk={riskLabelForPrep} className={glassRiskTone(risk.tone)} />
            </div>
          </div>
        </div>

        <div className="mt-6 text-xs" style={{ color: "var(--muted)" }}>
          Next upgrades: real data ingest(COMPLETED), persistent event log, threshold editor, and alerts.
        </div>
        <div className="mt-2 text-xs" style={{ color: "var(--muted)" }}>
          This site contains affiliate links. We may earn a commission from qualifying purchases.
        </div>
      </div>
    </div>
  );
}
